---
abstract: >
  This chapter reviews and summarises the findings of the PhD, returning to the controversial prison release described in the Introduction and considering why the retributive emotions it summoned in victims and the public were so outraged by the case. It identifies the limitations of the research, and comments on the originality and wider significance of the findings.
identifier-prefix: '7.'
keywords: [penal theory, murder, public wrongs, private wrongs, retribution]
#thanks: [Insert acknowledgements footnote after document title]
title: Conclusions
---

Jill Stauffer's book, *Ethical Loneliness* [-@staufferEthicalLonelinessInjustice2015, chap. 5], describes what happens when institutions fail to listen well to individual experiences of serious wrongdoing. By superimposing their own objectives on the messy realities of the individual case, they deal a double injustice: claiming the sole right to respond to the wrong; and then failing to consider the complexities of what those involved are owed. Instead of responding to real wrongs, institutions attempt to transform them into something tractable, and respond to that. Echoing the classic characterisation by Nils @christieConflictsProperty1977 of 'conflicts as property', @staufferEthicalLonelinessInjustice2015 [pp. 142-3] uses retributive punishment as an example:

  > [R]evenge disappears from official accounts of justice—beginning as a virtue and an honour owed to friends and kin, slowly converted into a formalized retribution owned only by the state (because, the reasoning goes, personal revenge is savagery), which then gets replaced by utilitarian calculations of social utility (because, the reasoning goes, retribution is also savage, or at least “not useful”). When revenge is virtue and honour, it is meted out personally between those affected, both victim (or the victim's champions) and perpetrator equally involved. When revenge becomes state retribution it pits state against perpetrator, placing the need to rebalance state order higher than the right a victim once had to claim satisfaction for loss undergone. When state retribution becomes calculations about deterrence and incapacitation, not only do victims disappear, but individual perpetrators matter less as well. State power remains. 

Stauffer suggests that one remedy is to take more seriously both resentment and the desire for revenge. These moral emotions *cannot be extinguished*, but if they are addressed, not merely bypassed, retribution "need not [be the] antonym of repair" [-@staufferEthicalLonelinessInjustice2015, p. 144]. The current default response---massive retaliatory harm against the most culpable party---can be mitigated.[^7.1] Retribution understood in these terms might mete out to *all* parties (and not merely the offender) what they deserve; and what offenders deserve might include not merely retaliation, but moral recognition, as people with the capacity to be accountable, and opportunities to regain trust.

The value of this argument is to redirect critical attention to what is ugly and problematic about retributive punishment: *not* that it inflicts damage on the culpable, but that it does so *without mitigation, remedy, or the opportunity for repair*. This is scarcely a promising circumstance in which a society can communicate about its values, and it may be partly for this reason that the 'new penology' rationales for imprisoning dangerous and risky populations have become highly incapacitative, basing themselves on a conceptualisation of offenders as dangerous objects, not as responsible subjects.

## Summarising the findings {.unnumbered}

The PhD illuminates how this shift towards a morally denuded, risk-focused form of life imprisonment has affected the coherence of the life sentence *as a retributive punishment*, which is to say, as a sanction aiming (in part) to communicate with lifers about wrongs, and the responsibilities which arise from them. It largely fails in this aim: it does not consistently push them to engage with their *particular* offence or to think about it as generating obligations towards *particular* victim(s). Some do think in this way. But this occurs haphazardly, and not by design.

Returning to the original research questions in Chapter [-@sec-2-research-questions], we can summarise answers as follows:

* men respond ethically in quite diverse ways to serving the mandatory life sentence;
  * they receive inconsistent and unclear moral messages about the offence of murder and their own past conduct, with more intense attempts at moral communication linked to assessed risk;
  * they respond to these messages according to a complex range of factors, among which both pre-prison social identity (linked to age at conviction) and the nature of the index offence are particularly significant;
  * they adopt highly individual ground projects and ethical priorities in response, but are pushed during ethical 'crunch points' to shape these to institutional requirements; and
  * official forms of moral communication often attempt to fit their specific actions to a broad, abstract template, leading some to feel misrecognised, and to find it difficult to make their prison experiences meaningful.

These findings were presented in stages. [Chapter 2](./2_literature-review.qmd) identified the moral nuance concealed beneath the single penalty for murder, suggesting that a systemic preoccupation with cost-effectiveness in risk management and intervention had rendered the penalty both increasingly severe, and yet also communicatively 'thin'. [Chapter 3](./3_methodology.qmd) set out the methodological underpinnings for the research, and Chapters [4](./4_becoming-a-murderer.qmd), [5](./5_life-and-the-life-sentence.qmd), and [6](./6_risk-and-self-governance.qmd) set out the empirical analysis.

Collectively, they concur with previous research on several points: that life imprisonment induces moral reflexivity; that enforced dislocation from previous patterns of activity and identity is central to this process; and that adaptation to a very long (and especially an indeterminate) sentence is influenced by an 'offence-time nexus' [@creweLifeImprisonmentYoung2020]. However, each one adds nuance. A focus on ethical reflexivity, as conceptualised using anthropological materials in Chapter [-@sec-2-concepts-practices-ethics], reveals the *content* of moral reflection to be varied, and strongly shaped by both the circumstances of the offence, and the life course before conviction. [Chapter 4](./4_becoming-a-murderer.qmd) showed that not all forms of violence are equally easy to account for---in the sense that doing so involves *explaining oneself to others*. On the life course, [Chapter 5](./5_life-and-the-life-sentence.qmd) noted variations based on age at conviction, broadly showing that lifers convicted younger thought of preparing for the future [as @creweLifeImprisonmentYoung2020, among others, have shown], while those convicted older found this idea less convincing, and often remained rooted in past identity. In relation to risk management, [Chapter 6](./6_risk-and-self-governance.qmd) introduces the concept of ethical 'crunch points' to suggest that 'tight' risk management, while certainly an explicit feature of policy, is neither implemented consistently, nor definitive of the experience of all lifers at all times during the sentence. Instead, psychological or 'soft' power may be more and less 'present' and 'absent', similarly to the power of officers [@creweHeavylightAbsentpresentRethinking2014]. This has implications for its legitimacy, since *both* the absence of intervention and the under-use of power can be just as harmful as their over-use, particularly if they are applied inconsistently through a very long sentence.

## Limitations {.unnumbered}

Naturally, there are limitations to these finding. Most importantly, these arise from the idiosyncrasies of the sample. Although the sample itself (as @sec-apx-c shows in detail) fairly closely represents the mandatory lifer populations of the two prisons on a range of sentence and demographic variables, the prisons themselves were unusual. Swaleside---an unusually short-staffed long-term prison with a history of violence and disorder---may be 'laxer' than many comparable sites. Leyhill---holding men with a complex risk profile whose resettlement was a challenging task---may have been unusually 'tight' compared to comparable prisons. A further limitation of the sample may arise from the uneven representation across sentence stages of participants with comparable offence types. Had the pandemic not intervened, this might have been possible to remedy in a third prison, but the questions begged are for others to take up.

Further limitations arise from the mix of documents made available to me by the OMUs in each prison. In [Chapter 6](./6_risk-and-self-governance.qmd), the portrait of Swaleside's 'looseness' or 'laxity'  is less textured than that of Leyhill's 'tightness'. At least in part, this will reflect its being painted from RC1 forms, not the EBM and ROTL risk assessments reviewed at Leyhill. The RC1 is a summary, albeit one presented to prisoners as if it speaks for itself, and at Swaleside, OASys and other more detailed assessments were subject to major backlogs. Records from psychological assessments or OBPs, even in digested form, were not available for review. This makes for identifiable blind spots in my view of moral communication about risk at Swaleside. The messages *received* in OBPs and through psychological assessments at Swaleside *were* evident in interview data, but glimpses of the censure they 'spoke' were fleeting. Other source materials might have yielded more textured insight, but this can only be speculative.

## Originality and wider significance {#sec-7-wider-significance .unnumbered}

Regardless of these limitations, the PhD has wider significance, primarily for the study of LTI. Ethnographic accounts of life in long-term prisons have traditionally focused on social dynamics, and the kinds of action prisoners engage in. Interest in the (re)construction of identity, and in interiority and reflexivity, has developed more recently.

The PhD adds to this body of recent work, in several ways. Its originality lies in the structured and systematic attention paid to how two factors---age at conviction and the life course---affect adaptation. It also lies in the account of moral communication presented here, in which messages delivered incoherently by the sanction interact with more personal and interior forms of reflection, sometimes producing self-reproach, but often not. 

Methodologically, this contributes to the study of LTI, by underlining the quite substantial variation within the population of interest. Recent contributions have theorised quite broadly about adaptation and related concepts, based on samples whose idiosyncratic specificities may not be obvious. John Irwin's [-@irwinLifersSeekingRedemption2009] seminal book *Lifers* is a good example; his theorisation of 'awakening' may reflect the particularities of San Quentin State Prison in California, with its relatively high concentration of prisoner-led programming and (perhaps) a *prisoner culture* which promoted reflection on the offence in a relatively unusual way. Similarly, @creweLifeImprisonmentYoung2020 develop a broad theorisation based not on a distinctive site, but on a distinctive sample: lifers convicted aged under 25. Both works are highly instructive, but the variability treated within this sample both refines and (sometimes) questions their theoretical conclusions; and this variation matters, since it affects the kinds of individual adaptations to imprisonment that lifers and LTPs have long been known to make. Future studies will need to keep the diversity of the LTP population within scope, not least because the population of interest may have bifurcated, between those convicted young and those convicted old, with sentencing law taking an invariant approach to determining the severity of their tariffs.

Theoretically and conceptually, the PhD contributes to the field by offering insights into reflexivity, an implicit but often underdeveloped theme in earlier research. As presented in these pages, ethical reflection---people's self-evaluations and the selfhoods they desire based on these---exerts a major influence over how they respond to censure and to its demands. We can only get so far with understanding this process---which drives how people 'do' their time in prison---without asking, in quite some detail, about the sense-making they engage in, and the representations of themselves they encounter in prison life. The power relations through which they encounter censure are those of incentives and 'soft' power [@creweSoftPowerPrison2011], but their responses are often quite individual and personal.

An attentiveness to ethics, as understood through anthropological texts on the subject, helps us 'get inside' these individual responses. For example, the cultural embeddedness of morality [@keaneEthicalLifeIts2016] helps make sense of how lifers rationalise the index offence, and yet also explains why dislocation from earlier lives can induce re-evaluation. Its emphasis on biographical narratives and projects of care as key vectors for ethics [@mattinglyMoralLaboratoriesFamily2014] can help understand adaptive differences between those who arrive in prison with their adult lives mostly unwritten, and those who arrive with them largely complete. Its emphasis on interaction and encounter as ethically fertile domains [@keaneEthicalLifeIts2016], and on 'exemplars' as the bearers of moral values [@robbinsWhereWorldAre2018] can make further sense of prisoners' 'redemption scripts' [@marunaMakingGoodHow2001], particularly those in which individuals who demand accountability compassionately appear as key figures [e.g. @jamesRedeemableMemoirDarkness2016]. And its account of first-person ethics---its contingency, and its 'tragic' vagaries [e.g. @mattinglyTwoVirtueEthics2012, 167-179]---enriches our understanding of how lifers think about their offending, especially when compared to barren and dismissive concepts such as "cognitive distortions" or even "neutralisations".

More broadly, the PhD has implications for how we understand the moral communication that retributive punishment is supposed to engage in. In a recent inquiry report on public understanding of sentencing, the House of Commons Justice Committee [-@houseofcommonsjusticecommitteePublicOpinionUnderstanding2023, paras. 51-79] recommended the publication and broadcast of judicial sentencing remarks, as a matter of course and not merely in high-profile cases (as has hitherto been the practice). They envisaged benefits for the media (para. 54); for victims and their families (para. 55-58, 60-65); and, as an afterthought, for defendants and prisoners (paras. 66-71). The Committee's concerns---that offenders often do not understand "the sentencing process" (para. 66)---are expressed in relation to understanding of *the structure of the sentence itself*:

  > It is important that offenders understand the sentence they are to serve. Offenders should have ready access to information about the sentencing process […] [and] about what their sentence will look like in practice. Offenders […] should be given a hard copy of their sentencing remarks.
  >
  > @houseofcommonsjusticecommitteePublicOpinionUnderstanding2023 [para. 71]

Understanding of the sentence *is* important: as [Chapter 6](./6_risk-and-self-governance.qmd) noted, a few participants at both fieldwork sites had gone some years in prison before grasping the indeterminacy of their life sentences. However, recent empirical research on moral communication, including this PhD, points to a *wider*, and less tractable, problem: the sanction's failure to communicate effectively or coherently that the state punishes lifers *for wronging fellow citizens*, not just for 'being dangerous' or 'being bad'.

Generally, sentencing remarks feature a narrative linking key features of the offence to the tariff selected. The Committee's recommendation on hard copies for prisoners goes some way to clarifying *what is being punished*, then. But it does little to clarify the delivery of censure because sentencing remarks are not static, and do not deliver censure as a one-off. Instead, they are reiterated and repackaged in risk assessment documents, where their summary of the court's fact-finding is marked by the adversarial trial's shortcomings as a truth-seeking procedure. Primarily concerned with judging legal guilt, it is uninterested in how the accused might understand their own actions (assuming they do). Procedural protections magnify this shortcoming, mediating expressions of responsibility through legal representation and ensuring that many defendants do not even speak. This forestalls opportunities to account for the offence, to express remorse, or to respond other than by denial.

The account which emerges may be highly tendentious and inauthentic, with no necessary link to what the offender thought he or she was doing. It then passes to the prison, where it is supplemented by files summarising the police investigation. These files, not necessarily tested in court, are not disclosable to the prisoner [@ministryofjusticeMultiAgencyLife2019]. In the hands of risk assessors, the result may be indirect and (sometimes) extrajudicial censure, which, over decades, coagulates into a kind of truth. The prisoner is defined by reference to a highly partial account of their index offence. Prison conduct, to the extent that it is recorded at all, is layered over it and interpreted in its light.

The process has elsewhere been described as 'maloptical'---that is, "the subject is seen badly, is seen *as* bad, and is projected and represented as bad" [@mcneillMassSupervisionMisrecognition2019, p. 209, emphasis original]. With LTPs and lifers, the process is particularly insidious, because of the well-documented ways in which these forms of imprisonment erase prisoners' pasts. Personhood comes gradually to be defined by an account which was partial to start with, and is then distorted through repetition. Communicatively, the result is evident in Chapters [4](./4_becoming-a-murderer.qmd) and [6](./6_risk-and-self-governance.qmd): lifers who did not recognise themselves or their experiences in the official account of the offence simply felt as if censure talked past them.

Thus, sentencing remarks do not state censure conclusively, but merely become the first step in a game of pass-it-on. Hard copies do not prevent this; the game communicates indifference to particularity, accuracy, individuality, subjectivity, context, and detail, and at worst, the resulting distortion of wrongs and responsibilities might satisfy no one. The concrete, personal, individual, tangible harms and wrongs censured by judges are converted by penal professionals into abstract, impersonal, aggregate, potential, and intangible management problems. The result is not necessarily moral accountability, of the kind Danielle @seredWeReckonViolence2019 describes.[^7.2]

Jill Stauffer's argument is that institutions often fail to listen well. Arguably, the life sentence fails to listen at all, at least not in any truly individualised way. Lifers are addressed too generally, too stereotypically, and too inconsistently for claims of individual accountability to be credible. This is because, arguably, too, the sentence expresses indifference to their response [see @brownleeOffenderPartDialogue2011]: it intervenes too little to support claims of transformation, and 'fixes' risk only in the sense of encasing prisoners in an account derived from the offence.

It has long been known that a long (and particularly, an indeterminate) sentence damages identity and relationships, ruptures lives, and imposes stigma. What is clearer after this PhD is that it does so while communicating incoherently. Through risk management practices, it increasingly manages *public wrongs*, rather than punishing the *private wrongs* which generated the sanction. As Jill Stauffer's account of 'thin' retribution suggests, this might suit the priorities of public bodies which direct and administer the sentence. But the overweening, hubristic ambition of risk management---to 'manage the custodial sentence' from end to end [@ministryofjusticeManageCustodialSentence2018]---is ill-supported by resourcing and expertise adequate to the task. Continuing sentence inflation further complicates matters by ensuring that there is less and less to work towards. Amid a scarcity of truly individual attention while they are in custody, these factors render it very difficult indeed for lifers to salvage a viable life following release.

## References {.unnumbered}

[^7.1]: Stauffer, for example, suggests support, moral recognition, or compensation.

[^7.2]: Quoted at the very end of [Chapter 4](./4_becoming-a-murderer.qmd).