---
number-sections: false
keywords: ""
---

## Abbreviations {.unnumbered .unlisted}

+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ATB           | Attitudes, Thinking and Behaviour, a department of HMP Swaleside tasked with delivering OBPs                                                                                                                                                             |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| CALM          | Controlling Anger and Learning to Manage it, an OBP                                                                                                                                                                                                      |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| CCRC          | Criminal Cases Review Commission, a body tasked with referring possible miscarriages of justice to the appeals courts                                                                                                                                    |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| DHL           | Logistics firm which holds the supplier contract for prisoner canteen orders, and operates workshops in both fieldwork prisons                                                                                                                           |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| DSPD          | Dangerous and Severe Personality Disorder, a superseded but still colloquial term used to describe both prisoners with this diagnosis and the specialist prison units used to treat them; see PIPE                                                       |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| EBM           | Enhanced Behaviour Monitoring, a supervision measure used in open prisons                                                                                                                                                                                |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ETE           | Education, Training, and Employment                                                                                                                                                                                                                      |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ETS           | Enhanced Thinking Skills, an OBP                                                                                                                                                                                                                         |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| FIFA          | A football-themed video game (referred to in interview quotes from Swaleside)                                                                                                                                                                            |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| HMP           | His Majesty’s Prison                                                                                                                                                                                                                                     |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| HMPPS         | His Majesty’s Prison & Probation Service                                                                                                                                                                                                                 |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| IEP           | Incentives and Earned Privileges, the now-superseded but still-colloquial name for behavioural incentives schemes used by all prisons                                                                                                                    |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| IPP           | Imprisonment for Public Protection, a form of indeterminate sentence                                                                                                                                                                                     |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| LTHSE         | Long-term and High-Security Estate, an organisational unit of HMPPS                                                                                                                                                                                      |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| LTI           | Long-Term Imprisonment                                                                                                                                                                                                                                   |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| LTP           | Long-Term Prisoner                                                                                                                                                                                                                                       |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| NHS           | National Health Service                                                                                                                                                                                                                                  |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| NRC           | National Research Committee of HMPPS                                                                                                                                                                                                                     |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| OASys         | Offender Assessment System, the overarching risk and needs assessment tool used by HMPPS                                                                                                                                                                 |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| OBP           | Offending Behaviour Programme, a risk-reducing intervention used by HMPPS                                                                                                                                                                                |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| OGP           | OASys General reoffending Predictor, an actuarial risk assessment methodology employing static and dynamic risk factors                                                                                                                                  |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| OGRS3         | revised Offender Group Reconviction Score, an actuarial risk assessment methodology employing only static risk factors                                                                                                                                   |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| OVP           | OASys Violence Predictor, an actuarial risk assessment methodology employing static and dynamic risk factors                                                                                                                                             |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| OMU           | Offender Management Unit—the department in all prisons tasked with risk assessment and management                                                                                                                                                        |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| P- or C-NOMIS | National Offender Management Information System, a prison database                                                                                                                                                                                       |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| PE            | Physical Education                                                                                                                                                                                                                                       |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| PIPE          | Psychologically Informed Planned Environment, a form of prison treatment unit combining prison and NHS provision, originally pioneered through DSPD provision, and operating Progression or Pathways regimes in numerous prisons including HMP Swaleside |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| PNC           | Police National Computer, the national criminal records database                                                                                                                                                                                         |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| POM           | Prison Offender Manager, a role for staff in OMUs                                                                                                                                                                                                        |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| PQ            | Pain Quotient (see O’Donnell 2014)                                                                                                                                                                                                                       |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| RC1           | Security recategorisation form used by OMUs                                                                                                                                                                                                              |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ROTL          | Release on Temporary Licence, aka temporary release from prison, usually for resettlement purposes                                                                                                                                                       |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| RoSH          | Risk of Serious Harm, a risk assessment methodology employing static and dynamic risk factors                                                                                                                                                            |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| RR            | Risk Reduction or Risk-Reducing                                                                                                                                                                                                                          |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| SMART         | Specific, Measurable, Achievable, Realistic, and Time-Bound, a target-setting methodology required by sentence planning policies                                                                                                                         |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| TC            | Therapeutic Community, a holistic approach to long-term RR work and a metonym for prison units where this work takes place                                                                                                                               |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| TSP           | Thinking Skills Programme, an OBP                                                                                                                                                                                                                        |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| UK            | United Kingdom                                                                                                                                                                                                                                           |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| US            | United States                                                                                                                                                                                                                                            |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
