## Demographic overview of sample members {.appendix}

To give an overview, and for reference, @tbl-apx5 shows key demographic information relating to the conviction and the pre-prison life course, for members of the entire sample at both prisons.

::: {.column-page}
|  Prison   | Pseudonym |        Ethnicity        | Age at interview | % of tariff served | Sentence stage |  Offence type[^apx1]  | Considers himself guilty of murder?[^apx1] | Age at sentencing | Highest education completed before conviction | Marital status before conviction | Custody of any children | Employment status before conviction | Previous prison sentences | Age at first conviction |
| :-------: | :-------: | :---------------------: | :--------------: | :----------------: | :------------: | :-------------------: | :----------------------------------------: | :---------------: | :-------------------------------------------: | :------------------------------: | :---------------------: | :---------------------------------: | :-----------------------: | :---------------------: |
| Swaleside |   Matt    |      White British      |      50-59       |         7%         |   Very early   |   Intimate partner    |                     y                      |       40-49       |        Trade/technical/vocational qual        |             Missing              |       no custody        |            self-employed            |            ---            |          10-19          |
| Swaleside |   Levi    | White & Black Caribbean |      20-29       |        10%         |   Very early   |  confrontation/fight  |                     y                      |       10-19       |           Secondary school, n quals           |      Single, never married       |           ---           |             unemployed              |            ---            |          10-19          |
| Swaleside |   Alan    |      White British      |      50-59       |        11%         |   Very early   |   Intimate partner    |                     y                      |       50-59       |        Trade/technical/vocational qual        |             Divorced             |     Adult children      |            self-employed            |            ---            |          40-49          |
| Swaleside |  Olivier  |      White British      |      60-64       |        16%         |   Very early   |   Intimate partner    |                  y and n                   |       60-64       |               Bachelors degree                | Married or domestic partnership  |     Adult children      |               retired               |            ---            |          20-29          |
| Swaleside |  Timothy  |       White Other       |      20-29       |        16%         |   Very early   |   Intimate partner    |                     n                      |       10-19       |                     GCSEs                     |      Single, never married       |           ---           |            f/t education            |            ---            |          10-19          |
| Swaleside |   Aftab   |     Asian Pakistani     |      30-39       |        21%         |     Early      |   Intimate partner    |                     n                      |       30-39       |               Bachelors degree                |             Widowed              |           ---           |             casual work             |            ---            |          30-39          |
| Swaleside |   Gary    |      White British      |      50-59       |        25%         |     Early      |  confrontation/fight  |                     y                      |       40-49       |                   A-levels                    |             Divorced             |       no custody        |             casual work             |            2-5            |          10-19          |
| Swaleside |  Yakubu   |      Black African      |      30-39       |        28%         |     Early      |  confrontation/fight  |                     n                      |       20-29       |               Bachelors degree                |      Single, never married       |       Daily care        |              employed               |            ---            |          20-29          |
| Swaleside |  Robert   |      White British      |      50-59       |        29%         |     Early      |  confrontation/fight  |                     y                      |       50-59       |              Professional degree              |             Divorced             |     Adult children      |             unemployed              |             1             |          30-39          |
| Swaleside |   Saeed   |     Asian Pakistani     |      40-49       |        31%         |     Early      |   Intimate partner    |                     n                      |       30-39       |                     GCSEs                     |            Separated             |       Daily care        |              employed               |             1             |          30-39          |
| Swaleside |  William  |      White British      |      40-49       |        32%         |     Early      |  confrontation/fight  |                  y and n                   |       30-39       |               Bachelors degree                |             Divorced             |       Daily care        |            self-employed            |             1             |          20-29          |
| Swaleside |   Rafiq   |    Asian Bangladeshi    |      30-39       |        33%         |     Early      |   Intimate partner    |                  y and n                   |       30-39       |              Professional degree              |             Widowed              |           ---           |              employed               |            ---            |          30-39          |
| Swaleside |   Liam    |      White British      |      40-49       |        36%         |      Mid       | Money/financial gain  |                     y                      |       30-39       |                     GCSEs                     |            Separated             |     Shared custody      |             unemployed              |            10+            |          10-19          |
| Swaleside |   Tony    |       White Irish       |      30-39       |        41%         |      Mid       |  confrontation/fight  |                     y                      |       20-29       |                     GCSEs                     |      Single, never married       |           ---           |             unemployed              |            2-5            |          10-19          |
| Swaleside |   Terry   |       White Irish       |      60-69       |        41%         |      Mid       |  confrontation/fight  |                  y and n                   |       50-59       |           Secondary school, n quals           | Married or domestic partnership  |       Daily care        |            self-employed            |            6-9            |          10-19          |
| Swaleside |  Reuben   |     Black Caribbean     |      30-39       |        43%         |      Mid       |  confrontation/fight  |                     n                      |       20-29       |        Trade/technical/vocational qual        |            Separated             |       Daily care        |            self-employed            |            ---            |          10-19          |
| Swaleside |    Ebo    |      Black African      |      20-29       |        45%         |      Mid       | Money/financial gain  |                  y and n                   |       10-19       |                     GCSEs                     |      Single, never married       |           ---           |             unemployed              |            ---            |          10-19          |
| Swaleside |   Adam    |      White British      |      20-29       |        46%         |      Mid       | Intensely stigmatised |                     y                      |       20-29       |                     GCSEs                     |      Single, never married       |           ---           |             unemployed              |            ---            |          20-29          |
| Swaleside |   Leon    |     Black Caribbean     |      40-49       |        47%         |      Mid       | Money/financial gain  |                     y                      |       20-29       |               Bachelors degree                |      Single, never married       |           ---           |             unemployed              |             1             |          10-19          |
| Swaleside |  Janusz   |       White Other       |      30-39       |        56%         |      Mid       | Intensely stigmatised |                     n                      |       30-39       |                     GCSEs                     |             Divorced             |       Daily care        |              employed               |            ---            |          30-39          |
| Swaleside |  Gerald   |      White British      |       65+        |        62%         |      Mid       |   Intimate partner    |                     y                      |       60-64       |              Professional degree              | Married or domestic partnership  |     Adult children      |               retired               |            ---            |          60-64          |
|  Leyhill  |  Dalton   |     Black Caribbean     |      30-39       |        67%         |      Mid       | Money/financial gain  |                     n                      |       20-29       |                   A-levels                    | Married or domestic partnership  |           ---           |             unemployed              |            ---            |          10-19          |
| Swaleside |   Billy   |      White British      |      40-49       |        71%         |      Late      |  confrontation/fight  |                     y                      |       30-39       |                     GCSEs                     |      Single, never married       |       no custody        |             unemployed              |            ---            |          10-19          |
|  Leyhill  |   Phil    |      White British      |      50-59       |        77%         |      Late      |  confrontation/fight  |                     y                      |       40-49       |           Secondary school, n quals           |      Single, never married       |       no custody        |              disabled               |            6-9            |          10-19          |
|  Leyhill  |    Kai    |      White British      |      30-39       |        77%         |      Late      |  confrontation/fight  |                     y                      |       20-29       |                    Diploma                    |      Single, never married       |       no custody        |             unemployed              |             1             |          10-19          |
|  Leyhill  |  Warren   |      White British      |      30-39       |        78%         |      Late      |  confrontation/fight  |                  y and n                   |       20-29       |        Trade/technical/vocational qual        |      Single, never married       |           ---           |              employed               |            ---            |          20-29          |
| Swaleside | Courtney  |     Black Caribbean     |      40-49       |        87%         |      Late      |  confrontation/fight  |                     n                      |       20-29       |                   A-levels                    |      Single, never married       |         Missing         |             unemployed              |             1             |          10-19          |
|  Leyhill  |    Alf    |      White British      |       65+        |        88%         |      Late      |  confrontation/fight  |                     y                      |        65+        |        Trade/technical/vocational qual        |             Divorced             |     Adult children      |               retired               |            ---            |           65+           |
|  Leyhill  |  Daniel   |      White British      |      50-59       |        88%         |      Late      | Intensely stigmatised |                     y                      |       30-39       |                    Diploma                    |             Divorced             |       Daily care        |            self-employed            |            ---            |          30-39          |
|  Leyhill  |   Dario   |      White British      |      40-49       |        89%         |      Late      |  confrontation/fight  |                     n                      |       20-29       |               Bachelors degree                |      Single, never married       |           ---           |              employed               |            ---            |          20-29          |
| Swaleside |  Simeon   |     Black Caribbean     |      20-29       |        92%         |      Late      |  confrontation/fight  |                     y                      |       10-19       |                     GCSEs                     |      Single, never married       |           ---           |            f/t education            |            ---            |          10-19          |
|  Leyhill  |  Taylor   |      White British      |      40-49       |        92%         |      Late      |  confrontation/fight  |                     y                      |       20-29       |        Trade/technical/vocational qual        |      Single, never married       |     Shared custody      |             unemployed              |            2-5            |          10-19          |
|  Leyhill  |   Grant   |      White British      |      50-59       |        93%         |      Late      |   Intimate partner    |                     y                      |       40-49       |        Trade/technical/vocational qual        |             Widowed              |       Daily care        |              employed               |            ---            |          40-49          |
| Swaleside |   Nasim   |     Black Caribbean     |      40-49       |        100%        |  Post-tariff   |  confrontation/fight  |                     y                      |       30-39       |        Trade/technical/vocational qual        |      Single, never married       |           ---           |               missing               |            2-5            |          10-19          |
| Swaleside |   Frank   |      White British      |      40-49       |        100%        |  Post-tariff   | Money/financial gain  |                     y                      |       20-29       |           Secondary school, n quals           |      Single, never married       |           ---           |             unemployed              |            2-5            |          10-19          |
|  Leyhill  | Jeremiah  |     Asian Pakistani     |      30-39       |        100%        |  Post-tariff   | Intensely stigmatised |                     n                      |       20-29       |        Trade/technical/vocational qual        |      Single, never married       |       no custody        |             unemployed              |            2-5            |          10-19          |
| Swaleside |   Nixon   |     Black Caribbean     |      40-49       |        106%        |  Post-tariff   | Money/financial gain  |                     n                      |       20-29       |                     GCSEs                     |      Single, never married       |     Shared custody      |             unemployed              |            2-5            |          10-19          |
|  Leyhill  |    Ron    |      White British      |      50-59       |        108%        |  Post-tariff   |  confrontation/fight  |                     y                      |       40-49       |           Secondary school, n quals           |             Divorced             |       no custody        |             casual work             |             1             |          10-19          |
| Swaleside |   Mark    |     Black Caribbean     |      30-39       |        113%        |  Post-tariff   |  confrontation/fight  |                     y                      |       20-29       |           Secondary school, n quals           |      Single, never married       |           ---           |             unemployed              |             1             |          10-19          |
|  Leyhill  |   Harry   |       White Other       |      50-59       |        129%        |  Post-tariff   | Intensely stigmatised |                     y                      |       30-39       |        Trade/technical/vocational qual        |      Single, never married       |       no custody        |             casual work             |            2-5            |          10-19          |
| Swaleside |    Tom    |      White British      |      50-59       |        129%        |  Post-tariff   | Intensely stigmatised |                     y                      |       30-39       |                   A-levels                    |      Single, never married       |       no custody        |             unemployed              |             1             |          10-19          |
|  Leyhill  |   Jeff    |     Black Caribbean     |      50-59       |        135%        |  Post-tariff   | Intensely stigmatised |                     y                      |       20-29       |                     GCSEs                     |      Single, never married       |       Daily care        |             unemployed              |            2-5            |          10-19          |
|  Leyhill  |    Ian    |       Not Stated        |      50-59       |        144%        |  Post-tariff   |   Intimate partner    |                     n                      |       30-39       |                    Diploma                    |             Divorced             |       Daily care        |              employed               |            ---            |          30-39          |
|  Leyhill  | Nicholas  |      White British      |      30-39       |        175%        |  Post-tariff   | Intensely stigmatised |                     y                      |       10-19       |                     GCSEs                     |      Single, never married       |           ---           |             casual work             |            ---            |          10-19          |
| Swaleside |   Chris   |      White British      |      60-64       |        180%        |  Post-tariff   |   Intimate partner    |                  y and n                   |       30-39       |                     GCSEs                     |             Missing              |     Shared custody      |            self-employed            |            ---            |          10-19          |
|  Leyhill  |   Emlyn   |       White Other       |       65+        |        230%        |  Post-tariff   |   Intimate partner    |                     n                      |       50-59       |                     GCSEs                     |             Widowed              |     Adult children      |              employed               |            ---            |          50-59          |
|  Leyhill  |   Fred    |      White British      |      50-59       |        238%        |  Post-tariff   | Intensely stigmatised |                     y                      |       20-29       |                   A-levels                    |      Single, never married       |           ---           |             unemployed              |            2-5            |          10-19          |
|  Leyhill  |   Derek   |      White British      |      50-59       |        250%        |  Post-tariff   | Intensely stigmatised |                     y                      |       20-29       |        Trade/technical/vocational qual        |      Single, never married       |           ---           |             unemployed              |             1             |          10-19          |


: An overview of basic demographic information for members of the sample. Ages over 65 are obfuscated to protect anonymity {#tbl-apx5}
:::

[^apx1]: See [Chapter 4](../4_becoming-a-murderer.qmd).